const mongoose = require('mongoose');

const BillSchema = mongoose.Schema({
	id: {
		type: String,
		index: true,
		unique: true,
	},
	customerId: {
		type: String,
		index: true,
		required: true,
	},
	invoiceNumber: {
		type: String,
		required: true,
	},
	invoiceDate: {
		type: Date,
		required: true,
	},
	dueDate: {
		type: Date,
		required: true,
	},
	totalAmount: {
		type: Number,
		required: true,
	},
	paymentStatus: {
		type: String,
		enum: ['pending', 'paid', 'overdue'],
		default: 'pending',
	},
	paymentDate: {
		type: Date,
	},
	paymentMethod: {
		type: String,
	},
	paymentReference: {
		type: String,
	},
  isAutoGenerated: {
    type: Boolean,
    default: false,
  },
  autoGenerateDate: {
    type: Date,
    default: new Date(),
  },
  autoGenerateDays: {
    type: Number,
    default: 30,
  },
}, { timestamps: true });

const Bill = mongoose.model('Bill', BillSchema);